### ISSUE TITLE
Cannot read properties of null (reading 'toString') in _cleanValueForRangeParse()

### ISSUE THREAD

**Issue by GiovanniBattista** [autoNumeric/autoNumeric#799]
### Current behavior
I have an autonumeric input field with the following options:
```js
  overrideMinMaxLimits: "invalid",
  emptyInputBehavior: "null",
```
When the input field is empty and I click inside it, the browser console throws the following error:
```js
autoNumeric.min.js:8 Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at Function.value (autoNumeric.min.js:8:178941)
    at Function.value (autoNumeric.min.js:8:179089)
    at e.value (autoNumeric.min.js:8:84240)
    at e.value (autoNumeric.min.js:8:98519)
    at HTMLInputElement._onFocusOutAndMouseLeaveFunc (autoNumeric.min.js:8:44598)
```
*Note: This error does not appear in the CodePen console.*

### Expected behavior
The `_cleanValueForRangeParse` function should handle `null` values gracefully and not attempt to call `.toString()` on them when the input is empty.

### Steps to reproduce the problem
1. Use autoNumeric version `v4.8.1`
2. In the browser `Chrome` version `130.0.6723.117`
3. On the `Windows` operating system
4. Then instantiate the autoNumeric object with the following options:
```js
new AutoNumeric(input, {
  overrideMinMaxLimits: "invalid",
  emptyInputBehavior: "null",
  isCancellable: false,
  oninvalidPaste: "ignore"
})
```
5. Observe the error in the browser's console:
```
Uncaught TypeError: Cannot read properties of null (reading 'toString')"
```

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
https://codepen.io/GiovanniBattista/pen/MWNzwXO

**Comment by melloware** [comment]
This was just reported as well in PrimeFaces: https://github.com/primefaces/primefaces/issues/14124

**Comment by melloware** [comment]
Thank you @AlexandreBonneau !
